export const navItems = [
  { path: "/", name: "Dashboard" },
  { path: "/chats", name: "Chats" },
  { path: "/users", name: "Users" },
  { path: "/disputes", name: "Disputes" },
  { path: "/transactions", name: "Transactions" },
  { path: "/orders", name: "Orders" },
  { path: "/recipes", name: "Recipes" },
  { path: "/employees/providers", name: "Provider Employees" },
  { path: "/employees", name: "Employees" },
  { path: "/translations", name: "Translations" },
  { path: "/notifications", name: "Notifications" },
];

export const users = [
  {
    id: 1,
    username: "username",
    country: "Poland",
    status: "active",
    role: "role",
    createdAt: new Date().getTime(),
  },
  {
    id: 2,
    username: "username",
    country: "Poland",
    status: "active",
    role: "role",
    createdAt: new Date().getTime(),
  },
  {
    id: 3,
    username: "username",
    country: "Poland",
    status: "active",
    role: "role",
    createdAt: new Date().getTime(),
  },
  {
    id: 4,
    username: "username",
    country: "Poland",
    status: "active",
    role: "role",
    createdAt: new Date().getTime(),
  },
  {
    id: 5,
    username: "username",
    country: "Poland",
    status: "active",
    role: "role",
    createdAt: new Date().getTime(),
  },
  {
    id: 6,
    username: "username",
    country: "Poland",
    status: "active",
    role: "role",
    createdAt: new Date().getTime(),
  },
  {
    id: 7,
    username: "username",
    country: "Poland",
    status: "active",
    role: "role",
    createdAt: new Date().getTime(),
  },
  {
    id: 8,
    username: "username",
    country: "Poland",
    status: "active",
    role: "role",
    createdAt: new Date().getTime(),
  },
  {
    id: 9,
    username: "username",
    country: "Poland",
    status: "active",
    role: "role",
    createdAt: new Date().getTime(),
  },
  {
    id: 10,
    username: "username",
    country: "Poland",
    status: "active",
    role: "role",
    createdAt: new Date().getTime(),
  },
];

export const url = "http://localhost:5000";
